### ISSUE TITLE
Articles don't refresh

### ISSUE THREAD

**Issue by esprehn** [Polymer/hn-polymer-2#3] opened 2017-05-19 23:24 UTC
Even after relaunching the app repeatedly it still shows an old list of Top articles. Looks like it's pulling stale data from an offline storage.

**Comment by azakus** [comment] 2017-05-20 01:50
Yeah, the sw-precache-config has "fastest" for each cache, which probably means the cache wins 100% of the time: https://github.com/Polymer/hn-polymer-2/blob/master/sw-precache-config.js#L25

**Comment by azakus** [comment] 2017-05-20 01:51
Edge caching for the API endpoint might also be doing the wrong thing

**Comment by esprehn** [comment] 2017-05-20 22:14
It's still stale to me now 24 hours later. So this seems like whatever is cached locally is always winning and it's never picking up new content. All the other HN apps seem to update, so it looks like something specific to what this one did.

**Comment by esprehn** [comment] 2017-05-29 19:11
This is still broken. The app is showing​ 10 day old articles still, and says "3 hours ago" even though the articles are  very old.

**Comment by azakus** [comment] 2017-05-30 17:38
Yep, still haven't had the time to fix the caching yet.

**Comment by azakus** [comment] 2017-05-30 21:10
Confirmed after reloading from new deployment

**Comment by sorvell** [comment] 2017-05-31 01:05
Re-opening as the Firebase function we're using still seems to be incorrectly over-caching. [This cache header](https://github.com/Polymer/hn-polymer-2/blob/master/functions/index.js#L15) looks like it's not being respected.

**Comment by azakus** [comment] 2017-05-31 19:09
Looks like this is a firebase issue w/edge caching headers conflicting with our cache-control header

**Comment by azakus** [comment] 2017-05-31 22:05
Ok, got word that this is fixed on the Firebase side now, so I'll redeploy and verify in a few minutes.

**Comment by azakus** [comment] 2017-05-31 22:43
Ok, looks like this is working now!

**Closed by azakus** 2017-05-31 22:43 UTC
